"""total amount nullable

Revision ID: 45f08b7bbbe1
Revises: c62f2cddd4db
Create Date: 2023-01-31 06:19:45.515475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45f08b7bbbe1'
down_revision = 'c62f2cddd4db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'total_amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'total_amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
